apiVersion: v1
kind: Secret
metadata:
  name: nest-kubernetes-app-secret
  namespace: nest-kubernetes-app
data:
  POSTGRES_PASSWORD: "bXlfcGFzc3dvcmQ="
  PGADMIN_DEFAULT_PASSWORD: "bXlfcGdfcGFzc3dvcmQ="
